terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/var/spool/slurm/job69717/slurm_script: line 7:  7156 Aborted                 ./main
